import bcrypt from 'bcryptjs';

const data = {
    users: [{

            name: 'jayesh',
            email: 'admin@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
            isSeller: true,
            seller: {
                name: 'Bajaj',
                logo: '/images/logo3.png',
                description: 'best seller',
                rating: 4.5,
                numReviews: 120,
            },
        },
        {
            name: 'John',
            email: 'user@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: false,
        },
    ],
    products: [{
            name: 'Bike 110CC Front Fork',
            category: 'Forks',
            image: '/images/Bike_110cc_FrontFork.png',
            price: 3000,
            countInStock: 40,
            brand: 'Yamaha',
            rating: 4.6,
            numReviews: 1120,
            description: 'This fork connects a front wheel and axle to its frame, typically via a yoke.',
        }, {
            name: 'Pulsar 180 Front Fork',
            category: 'Forks',
            image: '/images/Pulsar_180cc_FrontFork.png',
            price: 3300,
            countInStock: 40,
            brand: 'Bajaj',
            rating: 4.6,
            numReviews: 2120,
            description: 'This fork connects a front wheel and axle to its frame, typically via a yoke.',
        }, {
            name: 'Starcity+ Front Fork',
            category: 'Forks',
            image: '/images/TVS_Star_City_Plus_FrontFork.png',
            price: 2500,
            countInStock: 40,
            brand: 'TVS',
            rating: 4.6,
            numReviews: 720,
            description: 'This fork connects a front wheel and axle to its frame from TVS company, typically via a yoke.',
        },
        {
            name: 'Enduro Shock Absorbers',
            category: 'Shock Absorbers',
            image: '/images/Enduro_Shock_Absorbers3.png',
            price: 2500,
            countInStock: 14,
            brand: 'Enduro',
            rating: 4.5,
            numReviews: 10,
            description: 'this shock absobers are offfered by ENDURANCE brand. Enduro is the name that spells strength and the will to perform.',
        }, {
            name: 'RS200 Shock Absorbers',
            category: 'Shock Absorbers',
            image: '/images/Pulsar_Shock_Absorbers4.png',
            price: 3700,
            countInStock: 14,
            brand: 'Bajaj',
            rating: 4.8,
            numReviews: 540,
            description: 'this shock absobers are offfered by ENDURANCE brand. Enduro is the name that spells strength and the will to perform.',
        }, {
            name: 'Yamaha Shock Absorbers',
            category: 'Shock Absorbers',
            image: '/images/Shock_Absorbers2.png',
            price: 2000,
            countInStock: 14,
            brand: 'Yamaha',
            rating: 4.8,
            numReviews: 450,
            description: 'this shock absobers are offfered by ENDURANCE brand. Enduro is the name that spells strength and the will to perform.',
        },
        {
            name: 'Motorcycle Chain Sprocket',
            category: 'Sprockets',
            image: '/images/Motorcycle-Chain-Sprocket.png',
            price: 300,
            countInStock: 5,
            brand: 'Bajaj',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            name: 'Bajaj Engine',
            category: 'Engine',
            image: '/images/BAJAJ_Engine.png',
            price: 35000,
            countInStock: 15,
            brand: 'Bajaj',
            rating: 4.5,
            numReviews: 64,
            description: 'high quality product',
        }
    ],
};
export default data;